# Tarea 3: Redes Neuronales Artificiales

## Importación de DataFrame

In [139]:
import pandas as pd
from sklearn.model_selection import train_test_split
import sklearn as skl
import scipy as sci
import matplotlib.pyplot as plt
import numpy as np

DIR='C:\Projects\Physical_activity_classifier/Smartphone_Dataset'
df= pd.read_csv(DIR+'/S01/bike1.csv',header=None)
print(type(df))
data=df.as_matrix()
d_size=len(data)
#print(data)
final_data=[]
#Extract data for sensor
sensors=[[],[],[],[],[],[],[],[],[]]
for i in range(0,d_size):
    for j in range(0,9):
        sensors[j].append(data[i][j])

#---------------------mean-----------------------
ms=[]
for j in range(0,9):
    mean=np.mean(sensors[j])
    final_data.append(mean)
    ms.append(mean)
print('mean:[{},{},{},{},{},{},{},{},{}]'.format(ms[0],ms[1],ms[2],ms[3],ms[4],ms[5],ms[6],ms[7],ms[8]))
#---------------------Var------------------------    
vs=[]
for j in range(0,9):
    var=np.var(sensors[j])
    final_data.append(var)
    vs.append(var)
print('var:[{},{},{},{},{},{},{},{},{}]'.format(vs[0],vs[1],vs[2],vs[3],vs[4],vs[5],vs[6],vs[7],vs[8]))
#-------------------Entropy----------------------
Hs=[]
for j in range(0,9):
    H=sci.stats.entropy(sensors[j])
    #final_data.append(H)
    Hs.append(H)
print('H:[{},{},{},{},{},{},{},{},{}]'.format(Hs[0],Hs[1],Hs[2],Hs[3],Hs[4],Hs[5],Hs[6],Hs[7],Hs[8]))
#-------------------Kurtosis----------------------
Ks=[]
for j in range(0,9):
    K=sci.stats.kurtosis(sensors[j])
    final_data.append(K)
    Ks.append(K)
print('K:[{},{},{},{},{},{},{},{},{}]'.format(Ks[0],Ks[1],Ks[2],Ks[3],Ks[4],Ks[5],Ks[6],Ks[7],Ks[8]))
#-------------------Kurtosis----------------------
EEs=[]
for j in range(0,3):
    EE=0
    for i in range(0,d_size):
        EE+=(1/d_size)*np.sqrt(sensors[0+j*3][i]*sensors[0+j*3][i]+sensors[1+j*3][i]*sensors[1+j*3][i]+sensors[2+j*3][i]*sensors[2+j*3][i])
    #EE=sci.stats.kurtosis(sensors[j])
    #final_data.append(K)
    EEs.append(EE)
print('EE:[{},{},{}]'.format(EEs[0],EEs[1],EEs[2]))
    
#print(final_data)

<class 'pandas.core.frame.DataFrame'>
mean:[0.027909902,-0.99785272,-0.001931412,1.506938,1.265255174,-0.94328015,-25.469129999999996,-42.301207999999995,3.738514626]
var:[0.005201803730236396,0.009767228441801602,0.005743996674838256,0.002185380396,1.8675492931219797,1.5136131910446715,1.4289264010999991,0.3879815887359995,7.833129032443055]
H:[-inf,6.209660310234993,-inf,6.214115146148642,-inf,-inf,6.213506664555782,6.214499757896755,-inf]
K:[2.0797710132964573,0.1562451071595672,0.5480248396315996,5.056218202195623,0.11687826738541052,-1.1937164304285248,0.6256594305287222,1.8258631761652477,-0.6564941703619174]
EE:[1.0038016560590113,2.671732106662758,49.61547449898034]


In [192]:
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import sklearn as skl
import numpy as np
import scipy as sci

DIR='C:\Projects\Physical_activity_classifier/Smartphone_Dataset'
data= pd.read_csv(DIR+'/S01/bike1.csv',header=None)
#print(data)



x=[]
y=[]
for suj in range(1,10):#######################10
    for act in range(0,9):###################9
        Activities=['bike','climbing','descending','gymbike','jumping','running','standing','treadmill','walking']
        for k in range(1,6):
            path=DIR+'/S0'+str(suj)+'/'+Activities[act]+str(k)+'.csv'
            try:
                #Activity[j].append(pd.read_csv(path,header=None))
                df=pd.read_csv(path,header=None)
                
                #print(type(df))
                data=df.as_matrix()
                d_size=len(data)
                #print(data)
                final_data=[]
                #Extract data for sensor
                sensors=[[],[],[],[],[],[],[],[],[]]
                for i in range(0,d_size):
                    for j in range(0,9):
                        sensors[j].append(data[i][j])

                #---------------------mean-----------------------
                ms=[]
                for j in range(0,9):
                    mean=np.mean(sensors[j])
                    final_data.append(mean)
                    ms.append(mean)
                #print('mean:[{},{},{},{},{},{},{},{},{}]'.format(ms[0],ms[1],ms[2],ms[3],ms[4],ms[5],ms[6],ms[7],ms[8]))
                #---------------------Var------------------------    
                vs=[]
                for j in range(0,9):
                    var=np.var(sensors[j])
                    final_data.append(var)
                    vs.append(var)
                #print('var:[{},{},{},{},{},{},{},{},{}]'.format(vs[0],vs[1],vs[2],vs[3],vs[4],vs[5],vs[6],vs[7],vs[8]))
                #-------------------Entropy----------------------
                Hs=[]
                for j in range(0,9):
                    H=sci.stats.entropy(sensors[j])
                    #if(H==1):
                    #    print('hola')
                    #final_data.append(H)
                    Hs.append(H)
                #print('H:[{},{},{},{},{},{},{},{},{}]'.format(Hs[0],Hs[1],Hs[2],Hs[3],Hs[4],Hs[5],Hs[6],Hs[7],Hs[8]))
                #-------------------Kurtosis----------------------
                Ks=[]
                for j in range(0,9):
                    K=sci.stats.kurtosis(sensors[j])
                    final_data.append(K)
                    Ks.append(K)
                #print('K:[{},{},{},{},{},{},{},{},{}]'.format(Ks[0],Ks[1],Ks[2],Ks[3],Ks[4],Ks[5],Ks[6],Ks[7],Ks[8]))
                #-------------------Kurtosis----------------------
                EEs=[]
                for j in range(0,3):
                    EE=0
                    for i in range(0,d_size):
                        EE+=(1/d_size)*np.sqrt(sensors[0+j*3][i]*sensors[0+j*3][i]+sensors[1+j*3][i]*sensors[1+j*3][i]+sensors[2+j*3][i]*sensors[2+j*3][i])
                    #EE=sci.stats.kurtosis(sensors[j])
                    final_data.append(K)
                    EEs.append(EE)
                #print('K:[{},{},{}]'.format(EEs[0],EEs[1],EEs[2]))
                
                #-------------------Kurtosis----------------------
                RMSs=[]
                for j in range(0,9):
                    RMS=0
                    for i in range(0,d_size):
                        RMS+=np.sqrt((1/d_size)*sensors[j][i]*sensors[j][i])
                    #EE=sci.stats.kurtosis(sensors[j])
                    #final_data.append(RMS)
                    RMSs.append(RMS)
                #print('RMS:[{},{},{}]'.format(RMSs[0],RMSs[1],RMSs[2]))
                
                y.append(act)
                #print(final_data)
                x.append(final_data)
                
            except FileNotFoundError :
                print(path+' path doesn t exist')
        
    
print('Cantidad de datos: {}'.format(len(x)))
print('Cantidad de caracteristicas: {}'.format(len(x[0])))
#print('Datos por actividad: [{},{},{},{},{},{},{},{},{}]'.format(len(Activity[0]),len(Activity[1]),len(Activity[2]),len(Activity[3]),len(Activity[4]),len(Activity[5]),len(Activity[6]),len(Activity[7]),len(Activity[8])))
xtrain=x
ytrain=y
xval=[]
yval=[]
print(ytrain)

C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S02/gymbike1.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S02/gymbike2.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S02/gymbike3.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S02/gymbike4.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S02/gymbike5.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S03/treadmill3.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S04/bike1.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S04/bike2.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S04/bike3.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphone_Dataset/S04/bike4.csv path doesn t exist
C:\Projects\Physical_activity_classifier/Smartphon

In [193]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
import time
def ANN_train(xdata,ydata,hl_size=10,activation='relu'):
    clf = MLPClassifier(activation=activation,solver='lbfgs', hidden_layer_sizes=hl_size,
    early_stopping = True, validation_fraction = 0.20);
    #X, X_val, y, y_val = train_test_split(xdata, np.ravel(ydata), test_size=clf.validation_fraction);
    
    xtrain,xval,ytrain,yval=train_test_split(xdata,ydata,random_state=clf.random_state,
                                                       test_size=clf.validation_fraction)
    
    #print(y_val)
    #print('size: {}'.format(len(y_val)))
    
    start = time.clock()
    clf.fit(xtrain, np.ravel(ytrain))
    end = time.clock()
    dt=end-start
    return [clf,xtrain,xval,ytrain,yval,dt]
    

def ANN_perf(xtest,ytest,clf):
    ypred=clf.predict(xtest)
    c_m=confusion_matrix(ytest, ypred)
    return c_m

def get_D(c_m):
    dsum=0
    for i in range(0,len(c_m)):
        dsum+=c_m[i][i]
    return dsum

def get_Darray(c_m):
    D=[]
    for i in xrange(0,len(c_m)):
        D.append(c_m[i][i])
    return D

In [194]:
#hl_size_op=5000#(28+10)//2
hl_s=[20,500,1000]

print('-------------------------------------------------')
print('Neural Network')
print('-------------------------------------------------')

for i in range(0,3):
    clf,xtrain,xval,ytrain,yval,dt=ANN_train(x,y,hl_size=hl_s[i])
    
    c_m=ANN_perf(xval,yval,clf)
    print('Matriz de Confusión para {} neuronas'.format(hl_s[i]))
    print(c_m)
    dsum=get_D(c_m)
    percentage=np.round((dsum/(len(yval)*1.0))*100,4)
    print('Clasificaciones exitosas: {} de {}({}%)'.format(dsum,len(yval),percentage))
    print('Tiempo de entrenamiento: {}s'.format(dt))
    print('------------------------------------------------')

-------------------------------------------------
Neural Network
-------------------------------------------------
Matriz de Confusión para 20 neuronas
[[5 2 0 0 0 0 0 0 1]
 [0 5 0 0 0 0 0 0 0]
 [1 1 9 1 0 1 0 0 0]
 [2 0 1 7 0 0 0 0 1]
 [0 0 0 0 5 1 0 0 0]
 [0 0 0 0 2 5 0 0 0]
 [0 0 0 0 0 0 5 0 0]
 [0 1 0 0 1 1 0 7 0]
 [0 0 2 0 1 0 1 0 8]]
Clasificaciones exitosas: 56 de 77(72.7273%)
Tiempo de entrenamiento: 0.4348126956319902s
------------------------------------------------
Matriz de Confusión para 500 neuronas
[[ 4  0  0  0  0  0  0  0  0]
 [ 0  3  1  0  0  0  0  0  0]
 [ 0  1  8  1  0  0  0  0  0]
 [ 1  0  0  6  0  0  0  0  0]
 [ 1  0  0  0  6  2  0  0  1]
 [ 0  0  0  0  1  7  0  1  1]
 [ 1  0  1  2  0  0  9  0  0]
 [ 0  0  0  0  0  0  0 12  0]
 [ 1  0  1  0  0  0  0  1  4]]
Clasificaciones exitosas: 59 de 77(76.6234%)
Tiempo de entrenamiento: 4.050209311026265s
------------------------------------------------
Matriz de Confusión para 1000 neuronas
[[10  0  0  0  0  0  0  0  0]
 [ 

In [195]:
from sklearn.svm import SVC,LinearSVC
def svm_poly(xtrain,ytrain,xtest,ytest,deg=3):
    #Entrenamiento
    std_scale=skl.preprocessing.StandardScaler().fit(xtrain)
    df_std = std_scale.transform(xtrain)
    clf = SVC(kernel='linear',C=deg)
    clf.fit(df_std, ytrain)  
    #Validacion
    std_scale=skl.preprocessing.StandardScaler().fit(xtest)
    feattest = std_scale.transform(xtest)
    #score = clf_p.decision_function(feattest)
    #ypred=clf.predict(feattest)
    
    c_m=ANN_perf(xtest,ytest,clf)
    print('Matriz de Confusión:')
    print(c_m)
    dsum=get_D(c_m)
    percentage=np.round((dsum/(len(ytest)*1.0))*100,4)
    print('Clasificaciones exitosas: {} de {}({}%)'.format(dsum,len(ytest),percentage))
    #print('Tiempo de entrenamiento: {}s'.format(result[5]))
    
print('-------------------------------------------------')
print('Support Vector Machine')
print('-------------------------------------------------')
svm_poly(xtrain,ytrain,xval,yval,deg=0.0001)
print('-------------------------------------------------')
svm_poly(xtrain,ytrain,xval,yval,deg=1)
print('-------------------------------------------------')
svm_poly(xtrain,ytrain,xval,yval,deg=1000)
#svm_poly(Mtrain,Mval,deg=2)
#svm_poly(Mtrain,Mval,deg=3)

-------------------------------------------------
Support Vector Machine
-------------------------------------------------
Matriz de Confusión:
[[ 0 10  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0]]
Clasificaciones exitosas: 5 de 77(6.4935%)
-------------------------------------------------
Matriz de Confusión:
[[6 1 2 0 1 0 0 0 0]
 [0 5 0 0 0 0 0 0 0]
 [0 1 8 0 0 0 0 0 1]
 [2 0 2 0 0 0 0 0 0]
 [0 5 0 0 3 0 0 0 0]
 [0 1 2 0 2 0 0 1 1]
 [1 0 4 0 0 0 4 0 0]
 [0 5 3 0 0 0 0 7 0]
 [0 2 1 0 1 0 0 3 2]]
Clasificaciones exitosas: 35 de 77(45.4545%)
-------------------------------------------------
Matriz de Confusión:
[[4 1 3 0 2 0 0 0 0]
 [0 5 0 0 0 0 0 0 0]
 [0 1 8 0 0 0 0 0 1]
 [2 0 2 0 0 0 0 0 0]
 [0 5 0 0 3 0 0 0 0]
 [0 1 2 0 3 0 0 1 0]
 [2 0 6 0 0 0 0 1 0]
 [0 5 2 0 0 0 0 8 

In [196]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import GaussianNB
std_scale=skl.preprocessing.StandardScaler().fit(xtrain)
df_std = std_scale.transform(xtrain)
#X_train, X_test, y_train, y_test = train_test_split(df['Consumer_complaint_narrative'], df['Product'], random_state = 0)
#count_vect = CountVectorizer()
#X_train_counts = count_vect.fit_transform(X_train)
#tfidf_transformer = TfidfTransformer()
#X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
clf = GaussianNB().fit(df_std, ytrain)

#xtest=xtrain
#ytest=ytrain

std_scale=skl.preprocessing.StandardScaler().fit(xval)
feattest = std_scale.transform(xval)
#score = clf_p.decision_function(feattest)
#ypred=clf.predict(feattest)

c_m=ANN_perf(xval,yval,clf)

print('-------------------------------------------------')
print('Gaussian Naive Bayes')
print('-------------------------------------------------')

print('Matriz de Confusión:')
print(c_m)
dsum=get_D(c_m)
percentage=np.round((dsum/(len(yval)*1.0))*100,4)
print('Clasificaciones exitosas: {} de {}({}%)'.format(dsum,len(yval),percentage))
#print('Tiempo de entrenamiento: {}s'.format(result[5]))
    



-------------------------------------------------
Gaussian Naive Bayes
-------------------------------------------------
Matriz de Confusión:
[[ 0  1  0  0  0  9  0  0  0]
 [ 0  5  0  0  0  0  0  0  0]
 [ 0  3  3  0  0  4  0  0  0]
 [ 0  0  0  0  0  4  0  0  0]
 [ 0  1  1  0  0  6  0  0  0]
 [ 0  1  0  0  0  6  0  0  0]
 [ 0  0  0  0  6  3  0  0  0]
 [ 0  1  1  0  1 12  0  0  0]
 [ 0  2  0  0  1  6  0  0  0]]
Clasificaciones exitosas: 14 de 77(18.1818%)
